# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='',
  serialized_pb='\n\rmessage.proto\"9\n\x08hero_msg\x12\x0b\n\x03uid\x18\x01 \x02(\x05\x12\x0f\n\x07point_x\x18\x02 \x02(\x05\x12\x0f\n\x07point_y\x18\x03 \x02(\x05\":\n\tenemy_msg\x12\x0b\n\x03uid\x18\x01 \x02(\x05\x12\x0f\n\x07point_x\x18\x02 \x02(\x05\x12\x0f\n\x07point_y\x18\x03 \x02(\x05\":\n\tnew_enemy\x12\x0b\n\x03uid\x18\x01 \x02(\x05\x12\x0f\n\x07point_x\x18\x02 \x02(\x05\x12\x0f\n\x07point_y\x18\x03 \x02(\x05\"\x1a\n\x0b\x65nemy_leave\x12\x0b\n\x03uid\x18\x01 \x02(\x05\"\x19\n\tlogin_req\x12\x0c\n\x04name\x18\x01 \x02(\t\"^\n\tlogin_rsp\x12\x0f\n\x07success\x18\x01 \x02(\x08\x12\x0b\n\x03uid\x18\x02 \x02(\x05\x12\x0f\n\x07point_x\x18\x03 \x02(\x05\x12\x0f\n\x07point_y\x18\x04 \x02(\x05\x12\x11\n\tenemy_num\x18\x05 \x02(\x05\"\x1a\n\tstart_req\x12\r\n\x05start\x18\x01 \x02(\x08\"\x1a\n\tstart_rsp\x12\r\n\x05start\x18\x01 \x02(\x08\"\x1c\n\tlogin_end\x12\x0f\n\x07success\x18\x01 \x02(\x08\"\x18\n\tleave_req\x12\x0b\n\x03uid\x18\x01 \x02(\x05\"\x1a\n\tleave_rsp\x12\r\n\x05leave\x18\x01 \x02(\x08\"\x18\n\x08move_req\x12\x0c\n\x04move\x18\x01 \x02(\x05\"F\n\x08move_rsp\x12\x0f\n\x07success\x18\x01 \x02(\x08\x12\x0b\n\x03uid\x18\x02 \x02(\x05\x12\r\n\x05pos_x\x18\x03 \x02(\x05\x12\r\n\x05pos_y\x18\x04 \x02(\x05')




_HERO_MSG = _descriptor.Descriptor(
  name='hero_msg',
  full_name='hero_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='hero_msg.uid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point_x', full_name='hero_msg.point_x', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point_y', full_name='hero_msg.point_y', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=17,
  serialized_end=74,
)


_ENEMY_MSG = _descriptor.Descriptor(
  name='enemy_msg',
  full_name='enemy_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='enemy_msg.uid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point_x', full_name='enemy_msg.point_x', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point_y', full_name='enemy_msg.point_y', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=76,
  serialized_end=134,
)


_NEW_ENEMY = _descriptor.Descriptor(
  name='new_enemy',
  full_name='new_enemy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='new_enemy.uid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point_x', full_name='new_enemy.point_x', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point_y', full_name='new_enemy.point_y', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=136,
  serialized_end=194,
)


_ENEMY_LEAVE = _descriptor.Descriptor(
  name='enemy_leave',
  full_name='enemy_leave',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='enemy_leave.uid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=196,
  serialized_end=222,
)


_LOGIN_REQ = _descriptor.Descriptor(
  name='login_req',
  full_name='login_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='login_req.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=224,
  serialized_end=249,
)


_LOGIN_RSP = _descriptor.Descriptor(
  name='login_rsp',
  full_name='login_rsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='login_rsp.success', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uid', full_name='login_rsp.uid', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point_x', full_name='login_rsp.point_x', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='point_y', full_name='login_rsp.point_y', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enemy_num', full_name='login_rsp.enemy_num', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=251,
  serialized_end=345,
)


_START_REQ = _descriptor.Descriptor(
  name='start_req',
  full_name='start_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='start_req.start', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=347,
  serialized_end=373,
)


_START_RSP = _descriptor.Descriptor(
  name='start_rsp',
  full_name='start_rsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='start_rsp.start', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=375,
  serialized_end=401,
)


_LOGIN_END = _descriptor.Descriptor(
  name='login_end',
  full_name='login_end',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='login_end.success', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=403,
  serialized_end=431,
)


_LEAVE_REQ = _descriptor.Descriptor(
  name='leave_req',
  full_name='leave_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='leave_req.uid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=433,
  serialized_end=457,
)


_LEAVE_RSP = _descriptor.Descriptor(
  name='leave_rsp',
  full_name='leave_rsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='leave', full_name='leave_rsp.leave', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=459,
  serialized_end=485,
)


_MOVE_REQ = _descriptor.Descriptor(
  name='move_req',
  full_name='move_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='move', full_name='move_req.move', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=487,
  serialized_end=511,
)


_MOVE_RSP = _descriptor.Descriptor(
  name='move_rsp',
  full_name='move_rsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='move_rsp.success', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uid', full_name='move_rsp.uid', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos_x', full_name='move_rsp.pos_x', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos_y', full_name='move_rsp.pos_y', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=513,
  serialized_end=583,
)

DESCRIPTOR.message_types_by_name['hero_msg'] = _HERO_MSG
DESCRIPTOR.message_types_by_name['enemy_msg'] = _ENEMY_MSG
DESCRIPTOR.message_types_by_name['new_enemy'] = _NEW_ENEMY
DESCRIPTOR.message_types_by_name['enemy_leave'] = _ENEMY_LEAVE
DESCRIPTOR.message_types_by_name['login_req'] = _LOGIN_REQ
DESCRIPTOR.message_types_by_name['login_rsp'] = _LOGIN_RSP
DESCRIPTOR.message_types_by_name['start_req'] = _START_REQ
DESCRIPTOR.message_types_by_name['start_rsp'] = _START_RSP
DESCRIPTOR.message_types_by_name['login_end'] = _LOGIN_END
DESCRIPTOR.message_types_by_name['leave_req'] = _LEAVE_REQ
DESCRIPTOR.message_types_by_name['leave_rsp'] = _LEAVE_RSP
DESCRIPTOR.message_types_by_name['move_req'] = _MOVE_REQ
DESCRIPTOR.message_types_by_name['move_rsp'] = _MOVE_RSP

class hero_msg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HERO_MSG

  # @@protoc_insertion_point(class_scope:hero_msg)

class enemy_msg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENEMY_MSG

  # @@protoc_insertion_point(class_scope:enemy_msg)

class new_enemy(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NEW_ENEMY

  # @@protoc_insertion_point(class_scope:new_enemy)

class enemy_leave(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENEMY_LEAVE

  # @@protoc_insertion_point(class_scope:enemy_leave)

class login_req(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGIN_REQ

  # @@protoc_insertion_point(class_scope:login_req)

class login_rsp(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGIN_RSP

  # @@protoc_insertion_point(class_scope:login_rsp)

class start_req(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _START_REQ

  # @@protoc_insertion_point(class_scope:start_req)

class start_rsp(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _START_RSP

  # @@protoc_insertion_point(class_scope:start_rsp)

class login_end(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGIN_END

  # @@protoc_insertion_point(class_scope:login_end)

class leave_req(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LEAVE_REQ

  # @@protoc_insertion_point(class_scope:leave_req)

class leave_rsp(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LEAVE_RSP

  # @@protoc_insertion_point(class_scope:leave_rsp)

class move_req(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MOVE_REQ

  # @@protoc_insertion_point(class_scope:move_req)

class move_rsp(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MOVE_RSP

  # @@protoc_insertion_point(class_scope:move_rsp)


# @@protoc_insertion_point(module_scope)
